Added Carousel with React Slick library
iTjuana/itj-library pull request #71
Opened 2023-08-16 03:19 UTC by JordiEspinozaMendoza

### Description of the Change
Added Carousel component with React Slick library to display the books into the application.

Added carousel global style sheet to customize the component.

<img width="1317" alt="image" src="https://github.com/iTjuana/itj-library/assets/71615543/3bf51110-80f0-4d13-ab94-f1a373dee9c3">

### Verification Process

The component needs this props to work

```
CarouselProps {
  books: {
    title: string;
    image: string;
  }[];
  size?: "small" | "medium" | "large";
  dots?: boolean;
  speed?: number;
  slidesToShow?: number;
  slidesToScroll?: number;
  infinite?: boolean;
}
```

### Applicable Issues

- Closes #31 

### Release Notes

- Added Simple Carousel component

2023-08-16 03:43 UTC, Carmona-Daniel requested changes

2023-08-16 03:43 UTC, Carmona-Daniel commented on src/styles/carousel.css
Esto se puede pasar a tailwind?

2023-08-23 02:43 UTC, adlaiCarmona approved these changes

2023-08-23 02:44 UTC, NellyQuino approved these changes

2023-08-23 02:46 UTC, merged